# Generated by Django 5.1.6 on 2025-04-21 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_Details',
            fields=[
                ('farmer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('n', models.PositiveIntegerField()),
                ('p', models.PositiveIntegerField()),
                ('k', models.PositiveIntegerField()),
                ('temperature', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
                ('ph', models.CharField(max_length=20)),
                ('rainfall', models.CharField(max_length=20)),
                ('prediction', models.CharField(max_length=50)),
                ('fertilizer', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='fert_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('n', models.PositiveIntegerField()),
                ('p', models.PositiveIntegerField()),
                ('k', models.PositiveIntegerField()),
                ('temperature', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
                ('prediction', models.CharField(max_length=50)),
                ('fertilizer', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='images_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.FileField(upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='image_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.FileField(upload_to='crop_images/')),
                ('quantity', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
