# Generated by Django 5.1.6 on 2025-06-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop_Details',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
